---
# This role will install Func and start Func service funcd.

- name: Install Func package
  yum: name=func state=present

- name: Start Func funcd Service
  service: name=funcd state=started enabled=yes
